export const ADD_CONST_ID_LIST = 'ADD_CONST_ID_LIST';
export const CHANGE_SELECTED_SEAT = 'CHANGE_SELECTED_SEAT';
export const CURRENT_DURATION_SEATS = 'CURRENT_DURATION_SEATS';
export const SELECT_SEAT_POSITION = 'SELECT_SEAT_POSITION';
export const OLD_SEAT_ID = 'OLD_SEAT_ID';
export const ADD_OLD_SEATID_REQUIRED = 'ADD_OLD_SEATID_REQUIRED';

export const BUSINESS_SELECT_SEATLIST = 'BUSINESS_SELECT_SEATLIST';

export const SAVE_QUANTUM_ID = 'SAVE_QUANTUM_ID';
export const SAVE_CURRENTUSER_ID = 'SAVE_CURRENTUSER_ID';
export const ADD_STORE_SEAT_PRICE = 'ADD_STORE_SEAT_PRICE';
export const ADD_MOVIE_SINGLE_PRICE = 'ADD_MOVIE_SINGLE_PRICE';
export const CHANGE_STORE_TEMPLATE_TYPE = 'CHANGE_STORE_TEMPLATE_TYPE';
export const CHANGE_STORE_SEATLIST = 'CHANGE_STORE_SEATLIST';
export const CHANGE_STORE_SELECT_SEATLIST = 'CHANGE_STORE_SELECT_SEATLIST';

export const SAVE_SCHOOL_SCHEDULE_PAGE_SCHOOLID = 'SAVE_SCHOOL_SCHEDULE_PAGE_SCHOOLID';
export const GET_VIEW_STATUS = 'GET_VIEW_STATUS';
export const GET_CURRENT_LESSON = 'GET_CURRENT_LESSON';
export const GET_ALL_LESSON = 'GET_ALL_LESSON';
export const GET_TEACHER_LIST = 'GET_TEACHER_LIST';
export const GET_CURRENT_TEACHER = 'GET_CURRENT_TEACHER';
export const GET_ALL_VALID_MONTH = 'GET_ALL_VALID_MONTH';
export const GET_CURRENT_MONTH = 'GET_CURRENT_MONTH';
export const GET_CURRENT_CLASS_PLACE = 'GET_CURRENT_CLASS_PLACE';
export const GET_CURRENT_MONDAY = 'GET_CURRENT_MONDAY';
export const GET_CURRENT_SCHEDULE = 'GET_CURRENT_SCHEDULE';
export const GET_CURRENT_TEACHER_SCHEDULE = 'GET_CURRENT_TEACHER_SCHEDULE';
export const GET_LESSON_COLOR_MAP = 'GET_LESSON_COLOR_MAP';
export const GET_VALID_DURATION = 'GET_VALID_DURATION';

export const SAVE_TEACHER_PAGE_SCHOOLID = 'SAVE_TEACHER_PAGE_SCHOOLID';
export const GET_ALL_TEACHERS = 'GET_ALL_TEACHERS';
export const GET_CURRENT_TEACHERID = 'GET_CURRENT_TEACHERID';
export const GET_TEACHER_CURRENT_MONDAY = 'GET_TEACHER_CURRENT_MONDAY';
export const GET_TEACHER_SELECTED_DAY = 'GET_TEACHER_SELECTED_DAY';
export const GET_TEACHER_LESSONLIST = 'GET_TEACHER_LESSONLIST';

export const GET_USER_SCHEDULE_MONTH = 'GET_USER_SCHEDULE_MONTH';
export const GET_USER_SCHEDULE_MONDAY = 'GET_USER_SCHEDULE_MONDAY';
export const GET_USER_SCHEDULE_PLANNED_LIST = 'GET_USER_SCHEDULE_PLANNED_LIST';
export const GET_USER_SCHEDULE_UNPLANNED_LIST = 'GET_USER_SCHEDULE_UNPLANNED_LIST';

export const GET_MULTIPLE_DETAILS = 'GET_MULTIPLE_DETAILS';
export const GET_MULTIPLE_EXTRA = 'GET_MULTIPLE_EXTRA';
export const GET_MULTIPLE_SCHOOL = 'GET_MULTIPLE_SCHOOL';
export const GET_MULTIPLE_RECOMMEND = 'GET_MULTIPLE_RECOMMEND';
export const GET_MULTIPLE_TEACHER = 'GET_MULTIPLE_TEACHER';