export const ADD_USERID = 'ADD_USERID';
export const ADD_DURATION = 'ADD_DURATION';
export const CHANGE_VIEWSEAT_STATUS = 'CHANGE_VIEWSEAT_STATUS';
export const CHANGE_SELECTED_SEAT = 'CHANGE_SELECTED_SEAT';
export const CURRENT_DURATION_SEATS = 'CURRENT_DURATION_SEATS';

export const CHANGE_STORE_SEATLIST = 'CHANGE_STORE_SEATLIST';
export const CHANGE_STORE_SELECT_SEATLIST = 'CHANGE_STORE_SELECT_SEATLIST';

export const GET_VIEW_STATUS = 'GET_VIEW_STATUS';
export const GET_CURRENT_LESSON = 'GET_CURRENT_LESSON';
export const GET_ALL_LESSON = 'GET_ALL_LESSON';
export const GET_TEACHER_LIST = 'GET_TEACHER_LIST';
export const GET_CURRENT_TEACHER = 'GET_CURRENT_TEACHER';
export const GET_ALL_VALID_MONTH = 'GET_ALL_VALID_MONTH';
export const GET_CURRENT_MONTH = 'GET_CURRENT_MONTH';
export const GET_CURRENT_CLASS_PLACE = 'GET_CURRENT_CLASS_PLACE';
export const GET_CURRENT_MONDAY = 'GET_CURRENT_MONDAY';
export const GET_CURRENT_SCHEDULE = 'GET_CURRENT_SCHEDULE';
export const GET_CURRENT_TEACHER_SCHEDULE = 'GET_CURRENT_TEACHER_SCHEDULE';
export const GET_LESSON_COLOR_MAP = 'GET_LESSON_COLOR_MAP';
export const GET_VALID_DURATION = 'GET_VALID_DURATION';

export const GET_ALL_TEACHERS = 'GET_ALL_TEACHERS';
export const GET_CURRENT_TEACHERID = 'GET_CURRENT_TEACHERID';
export const GET_TEACHER_CURRENT_MONDAY = 'GET_TEACHER_CURRENT_MONDAY';
export const GET_TEACHER_SELECTED_DAY = 'GET_TEACHER_SELECTED_DAY';
export const GET_TEACHER_LESSONLIST = 'GET_TEACHER_LESSONLIST';

export const GET_USER_SCHEDULE_MONTH = 'GET_USER_SCHEDULE_MONTH';
export const GET_USER_SCHEDULE_MONDAY = 'GET_USER_SCHEDULE_MONDAY';
export const GET_USER_SCHEDULE_PLANNED_LIST = 'GET_USER_SCHEDULE_PLANNED_LIST';
export const GET_USER_SCHEDULE_UNPLANNED_LIST = 'GET_USER_SCHEDULE_UNPLANNED_LIST';